//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public string rfc { get; set; }
        public string razon_social { get; set; }
        public string representante { get; set; }
        public string calle { get; set; }
        public string no_ext { get; set; }
        public string no_int { get; set; }
        public string colonia { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string codigo_postal { get; set; }
        public string tel_principal { get; set; }
        public string e_mail { get; set; }
        public byte[] logo { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
