//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_venta
    {
        public int id_pos { get; set; }
        public System.Guid id_venta { get; set; }
        public long id_factura { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
