//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta_articulo
    {
        public System.Guid id_oferta { get; set; }
        public string cod_barras { get; set; }
        public decimal precio_oferta { get; set; }
        public string status_oferta { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual oferta oferta { get; set; }
    }
}
