//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_settings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_settings()
        {
            this.pos_control = new HashSet<pos_control>();
            this.venta_cancelada = new HashSet<venta_cancelada>();
            this.venta = new HashSet<venta>();
        }
    
        public int id_pos { get; set; }
        public string tipo_pago { get; set; }
        public bool tck_concentrado { get; set; }
        public bool inventario_online { get; set; }
        public Nullable<System.DateTime> corte_x { get; set; }
        public Nullable<System.DateTime> corte_y { get; set; }
        public string pos_dsp_name { get; set; }
        public bool pos_dsp_enable { get; set; }
        public string pos_ptr_name { get; set; }
        public bool pos_ptr_enable { get; set; }
        public bool pos_log_enable { get; set; }
        public string pos_csh_name { get; set; }
        public bool pos_csh_enable { get; set; }
        public string pos_scn_name { get; set; }
        public bool pos_scn_enable { get; set; }
        public long pos_folio { get; set; }
        public string win_ptr_name { get; set; }
        public bool win_ptr_enable { get; set; }
        public string com_name { get; set; }
        public string com_rate { get; set; }
        public Nullable<short> com_bits { get; set; }
        public string com_parity { get; set; }
        public string com_stop { get; set; }
        public bool com_enable { get; set; }
        public System.DateTime last_corte_z { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_control> pos_control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta_cancelada> venta_cancelada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
