//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_control
    {
        public System.Guid id_control_pos { get; set; }
        public int id_pos { get; set; }
        public string user_name { get; set; }
        public System.DateTime pos_open_date { get; set; }
    
        public virtual pos_settings pos_settings { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
