//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_permiso
    {
        public string user_name { get; set; }
        public string id_permiso { get; set; }
        public Nullable<decimal> valor_num { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual permiso permiso { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
