//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodeTech.Repository.PosCaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta_devolucion_articulo
    {
        public System.Guid id_devolucion { get; set; }
        public long no_articulo { get; set; }
        public string cod_barras { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual venta_devolucion venta_devolucion { get; set; }
    }
}
