#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuPlazaPOS35.DomainServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pos_admin")]
	public partial class pos_adminDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertarticulo(articulo instance);
    partial void Updatearticulo(articulo instance);
    partial void Deletearticulo(articulo instance);
    partial void Insertempleado(empleado instance);
    partial void Updateempleado(empleado instance);
    partial void Deleteempleado(empleado instance);
    partial void Insertempresa(empresa instance);
    partial void Updateempresa(empresa instance);
    partial void Deleteempresa(empresa instance);
    partial void Insertfactura_venta(factura_venta instance);
    partial void Updatefactura_venta(factura_venta instance);
    partial void Deletefactura_venta(factura_venta instance);
    partial void Insertoferta(oferta instance);
    partial void Updateoferta(oferta instance);
    partial void Deleteoferta(oferta instance);
    partial void Insertoferta_articulo(oferta_articulo instance);
    partial void Updateoferta_articulo(oferta_articulo instance);
    partial void Deleteoferta_articulo(oferta_articulo instance);
    partial void Insertpermiso(permiso instance);
    partial void Updatepermiso(permiso instance);
    partial void Deletepermiso(permiso instance);
    partial void Insertunidad_medida(unidad_medida instance);
    partial void Updateunidad_medida(unidad_medida instance);
    partial void Deleteunidad_medida(unidad_medida instance);
    partial void Insertusuario_permiso(usuario_permiso instance);
    partial void Updateusuario_permiso(usuario_permiso instance);
    partial void Deleteusuario_permiso(usuario_permiso instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
        #endregion


        

        public pos_adminDataContext() :
				base(SuPlazaPOS35.Settings.Default.pos_cajaConnectionString, mappingSource)
		{
			OnCreated();
		}
		public pos_adminDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pos_adminDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pos_adminDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pos_adminDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<articulo> articulo
		{
			get
			{
				return this.GetTable<articulo>();
			}
		}
		
		public System.Data.Linq.Table<empleado> empleado
		{
			get
			{
				return this.GetTable<empleado>();
			}
		}
		
		public System.Data.Linq.Table<empresa> empresa
		{
			get
			{
				return this.GetTable<empresa>();
			}
		}
		
		public System.Data.Linq.Table<factura_venta> factura_venta
		{
			get
			{
				return this.GetTable<factura_venta>();
			}
		}
		
		public System.Data.Linq.Table<oferta> oferta
		{
			get
			{
				return this.GetTable<oferta>();
			}
		}
		
		public System.Data.Linq.Table<oferta_articulo> oferta_articulo
		{
			get
			{
				return this.GetTable<oferta_articulo>();
			}
		}
		
		public System.Data.Linq.Table<permiso> permiso
		{
			get
			{
				return this.GetTable<permiso>();
			}
		}
		
		public System.Data.Linq.Table<unidad_medida> unidad_medida
		{
			get
			{
				return this.GetTable<unidad_medida>();
			}
		}
		
		public System.Data.Linq.Table<usuario_permiso> usuario_permiso
		{
			get
			{
				return this.GetTable<usuario_permiso>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.articulo")]
	public partial class articulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cod_barras;
		
		private string _cod_asociado;
		
		private long _id_clasificacion;
		
		private string _cod_interno;
		
		private string _descripcion;
		
		private string _descripcion_corta;
		
		private decimal _cantidad_um;
		
		private System.Guid _id_unidad;
		
		private System.Guid _id_proveedor;
		
		private decimal _precio_compra;
		
		private decimal _utilidad;
		
		private decimal _precio_venta;
		
		private string _tipo_articulo;
		
		private decimal _stock;
		
		private decimal _stock_min;
		
		private decimal _stock_max;
		
		private decimal _iva;
		
		private System.Nullable<System.DateTime> _kit_fecha_ini;
		
		private System.Nullable<System.DateTime> _kit_fecha_fin;
		
		private bool _articulo_disponible;
		
		private bool _kit;
		
		private System.DateTime _fecha_registro;
		
		private bool _visible;
		
		private short _puntos;
		
		private System.DateTime _last_update_inventory;
		
		private string _cve_producto;
		
		private EntitySet<articulo> _articulo2;
		
		private EntitySet<oferta_articulo> _oferta_articulo;
		
		private EntityRef<articulo> _articulo1;
		
		private EntityRef<unidad_medida> _unidad_medida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_barrasChanging(string value);
    partial void Oncod_barrasChanged();
    partial void Oncod_asociadoChanging(string value);
    partial void Oncod_asociadoChanged();
    partial void Onid_clasificacionChanging(long value);
    partial void Onid_clasificacionChanged();
    partial void Oncod_internoChanging(string value);
    partial void Oncod_internoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Ondescripcion_cortaChanging(string value);
    partial void Ondescripcion_cortaChanged();
    partial void Oncantidad_umChanging(decimal value);
    partial void Oncantidad_umChanged();
    partial void Onid_unidadChanging(System.Guid value);
    partial void Onid_unidadChanged();
    partial void Onid_proveedorChanging(System.Guid value);
    partial void Onid_proveedorChanged();
    partial void Onprecio_compraChanging(decimal value);
    partial void Onprecio_compraChanged();
    partial void OnutilidadChanging(decimal value);
    partial void OnutilidadChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void Ontipo_articuloChanging(string value);
    partial void Ontipo_articuloChanged();
    partial void OnstockChanging(decimal value);
    partial void OnstockChanged();
    partial void Onstock_minChanging(decimal value);
    partial void Onstock_minChanged();
    partial void Onstock_maxChanging(decimal value);
    partial void Onstock_maxChanged();
    partial void OnivaChanging(decimal value);
    partial void OnivaChanged();
    partial void Onkit_fecha_iniChanging(System.Nullable<System.DateTime> value);
    partial void Onkit_fecha_iniChanged();
    partial void Onkit_fecha_finChanging(System.Nullable<System.DateTime> value);
    partial void Onkit_fecha_finChanged();
    partial void Onarticulo_disponibleChanging(bool value);
    partial void Onarticulo_disponibleChanged();
    partial void OnkitChanging(bool value);
    partial void OnkitChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    partial void OnvisibleChanging(bool value);
    partial void OnvisibleChanged();
    partial void OnpuntosChanging(short value);
    partial void OnpuntosChanged();
    partial void Onlast_update_inventoryChanging(System.DateTime value);
    partial void Onlast_update_inventoryChanged();
    partial void Oncve_productoChanging(string value);
    partial void Oncve_productoChanged();
    #endregion
		
		public articulo()
		{
			this._articulo2 = new EntitySet<articulo>(new Action<articulo>(this.attach_articulo2), new Action<articulo>(this.detach_articulo2));
			this._oferta_articulo = new EntitySet<oferta_articulo>(new Action<oferta_articulo>(this.attach_oferta_articulo), new Action<oferta_articulo>(this.detach_oferta_articulo));
			this._articulo1 = default(EntityRef<articulo>);
			this._unidad_medida = default(EntityRef<unidad_medida>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_barras", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_barras
		{
			get
			{
				return this._cod_barras;
			}
			set
			{
				if ((this._cod_barras != value))
				{
					this.Oncod_barrasChanging(value);
					this.SendPropertyChanging();
					this._cod_barras = value;
					this.SendPropertyChanged("cod_barras");
					this.Oncod_barrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_asociado", DbType="VarChar(15)")]
		public string cod_asociado
		{
			get
			{
				return this._cod_asociado;
			}
			set
			{
				if ((this._cod_asociado != value))
				{
					if (this._articulo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_asociadoChanging(value);
					this.SendPropertyChanging();
					this._cod_asociado = value;
					this.SendPropertyChanged("cod_asociado");
					this.Oncod_asociadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_clasificacion", DbType="BigInt NOT NULL")]
		public long id_clasificacion
		{
			get
			{
				return this._id_clasificacion;
			}
			set
			{
				if ((this._id_clasificacion != value))
				{
					this.Onid_clasificacionChanging(value);
					this.SendPropertyChanging();
					this._id_clasificacion = value;
					this.SendPropertyChanged("id_clasificacion");
					this.Onid_clasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_interno", DbType="VarChar(15)")]
		public string cod_interno
		{
			get
			{
				return this._cod_interno;
			}
			set
			{
				if ((this._cod_interno != value))
				{
					this.Oncod_internoChanging(value);
					this.SendPropertyChanging();
					this._cod_interno = value;
					this.SendPropertyChanged("cod_interno");
					this.Oncod_internoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_corta", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string descripcion_corta
		{
			get
			{
				return this._descripcion_corta;
			}
			set
			{
				if ((this._descripcion_corta != value))
				{
					this.Ondescripcion_cortaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_corta = value;
					this.SendPropertyChanged("descripcion_corta");
					this.Ondescripcion_cortaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_um", DbType="Decimal(19,3) NOT NULL")]
		public decimal cantidad_um
		{
			get
			{
				return this._cantidad_um;
			}
			set
			{
				if ((this._cantidad_um != value))
				{
					this.Oncantidad_umChanging(value);
					this.SendPropertyChanging();
					this._cantidad_um = value;
					this.SendPropertyChanged("cantidad_um");
					this.Oncantidad_umChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_unidad", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id_unidad
		{
			get
			{
				return this._id_unidad;
			}
			set
			{
				if ((this._id_unidad != value))
				{
					if (this._unidad_medida.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_unidadChanging(value);
					this.SendPropertyChanging();
					this._id_unidad = value;
					this.SendPropertyChanged("id_unidad");
					this.Onid_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_compra", DbType="Decimal(19,3) NOT NULL")]
		public decimal precio_compra
		{
			get
			{
				return this._precio_compra;
			}
			set
			{
				if ((this._precio_compra != value))
				{
					this.Onprecio_compraChanging(value);
					this.SendPropertyChanging();
					this._precio_compra = value;
					this.SendPropertyChanged("precio_compra");
					this.Onprecio_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_utilidad", DbType="Decimal(19,3) NOT NULL")]
		public decimal utilidad
		{
			get
			{
				return this._utilidad;
			}
			set
			{
				if ((this._utilidad != value))
				{
					this.OnutilidadChanging(value);
					this.SendPropertyChanging();
					this._utilidad = value;
					this.SendPropertyChanged("utilidad");
					this.OnutilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Decimal(19,3) NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_articulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo_articulo
		{
			get
			{
				return this._tipo_articulo;
			}
			set
			{
				if ((this._tipo_articulo != value))
				{
					this.Ontipo_articuloChanging(value);
					this.SendPropertyChanging();
					this._tipo_articulo = value;
					this.SendPropertyChanged("tipo_articulo");
					this.Ontipo_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Decimal(19,3) NOT NULL")]
		public decimal stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this.OnstockChanging(value);
					this.SendPropertyChanging();
					this._stock = value;
					this.SendPropertyChanged("stock");
					this.OnstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_min", DbType="Decimal(19,3) NOT NULL")]
		public decimal stock_min
		{
			get
			{
				return this._stock_min;
			}
			set
			{
				if ((this._stock_min != value))
				{
					this.Onstock_minChanging(value);
					this.SendPropertyChanging();
					this._stock_min = value;
					this.SendPropertyChanged("stock_min");
					this.Onstock_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_max", DbType="Decimal(19,3) NOT NULL")]
		public decimal stock_max
		{
			get
			{
				return this._stock_max;
			}
			set
			{
				if ((this._stock_max != value))
				{
					this.Onstock_maxChanging(value);
					this.SendPropertyChanging();
					this._stock_max = value;
					this.SendPropertyChanged("stock_max");
					this.Onstock_maxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iva", DbType="Decimal(4,2) NOT NULL")]
		public decimal iva
		{
			get
			{
				return this._iva;
			}
			set
			{
				if ((this._iva != value))
				{
					this.OnivaChanging(value);
					this.SendPropertyChanging();
					this._iva = value;
					this.SendPropertyChanged("iva");
					this.OnivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kit_fecha_ini", DbType="DateTime")]
		public System.Nullable<System.DateTime> kit_fecha_ini
		{
			get
			{
				return this._kit_fecha_ini;
			}
			set
			{
				if ((this._kit_fecha_ini != value))
				{
					this.Onkit_fecha_iniChanging(value);
					this.SendPropertyChanging();
					this._kit_fecha_ini = value;
					this.SendPropertyChanged("kit_fecha_ini");
					this.Onkit_fecha_iniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kit_fecha_fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> kit_fecha_fin
		{
			get
			{
				return this._kit_fecha_fin;
			}
			set
			{
				if ((this._kit_fecha_fin != value))
				{
					this.Onkit_fecha_finChanging(value);
					this.SendPropertyChanging();
					this._kit_fecha_fin = value;
					this.SendPropertyChanged("kit_fecha_fin");
					this.Onkit_fecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articulo_disponible", DbType="Bit NOT NULL")]
		public bool articulo_disponible
		{
			get
			{
				return this._articulo_disponible;
			}
			set
			{
				if ((this._articulo_disponible != value))
				{
					this.Onarticulo_disponibleChanging(value);
					this.SendPropertyChanging();
					this._articulo_disponible = value;
					this.SendPropertyChanged("articulo_disponible");
					this.Onarticulo_disponibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kit", DbType="Bit NOT NULL")]
		public bool kit
		{
			get
			{
				return this._kit;
			}
			set
			{
				if ((this._kit != value))
				{
					this.OnkitChanging(value);
					this.SendPropertyChanging();
					this._kit = value;
					this.SendPropertyChanged("kit");
					this.OnkitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Bit NOT NULL")]
		public bool visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="SmallInt NOT NULL")]
		public short puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_update_inventory", DbType="DateTime NOT NULL")]
		public System.DateTime last_update_inventory
		{
			get
			{
				return this._last_update_inventory;
			}
			set
			{
				if ((this._last_update_inventory != value))
				{
					this.Onlast_update_inventoryChanging(value);
					this.SendPropertyChanging();
					this._last_update_inventory = value;
					this.SendPropertyChanged("last_update_inventory");
					this.Onlast_update_inventoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cve_producto", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cve_producto
		{
			get
			{
				return this._cve_producto;
			}
			set
			{
				if ((this._cve_producto != value))
				{
					this.Oncve_productoChanging(value);
					this.SendPropertyChanging();
					this._cve_producto = value;
					this.SendPropertyChanged("cve_producto");
					this.Oncve_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="articulo_articulo", Storage="_articulo2", ThisKey="cod_barras", OtherKey="cod_asociado")]
		public EntitySet<articulo> articulo2
		{
			get
			{
				return this._articulo2;
			}
			set
			{
				this._articulo2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="articulo_oferta_articulo", Storage="_oferta_articulo", ThisKey="cod_barras", OtherKey="cod_barras")]
		public EntitySet<oferta_articulo> oferta_articulo
		{
			get
			{
				return this._oferta_articulo;
			}
			set
			{
				this._oferta_articulo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="articulo_articulo", Storage="_articulo1", ThisKey="cod_asociado", OtherKey="cod_barras", IsForeignKey=true)]
		public articulo articulo1
		{
			get
			{
				return this._articulo1.Entity;
			}
			set
			{
				articulo previousValue = this._articulo1.Entity;
				if (((previousValue != value) 
							|| (this._articulo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._articulo1.Entity = null;
						previousValue.articulo2.Remove(this);
					}
					this._articulo1.Entity = value;
					if ((value != null))
					{
						value.articulo2.Add(this);
						this._cod_asociado = value.cod_barras;
					}
					else
					{
						this._cod_asociado = default(string);
					}
					this.SendPropertyChanged("articulo1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidad_medida_articulo", Storage="_unidad_medida", ThisKey="id_unidad", OtherKey="id_unidad", IsForeignKey=true)]
		public unidad_medida unidad_medida
		{
			get
			{
				return this._unidad_medida.Entity;
			}
			set
			{
				unidad_medida previousValue = this._unidad_medida.Entity;
				if (((previousValue != value) 
							|| (this._unidad_medida.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._unidad_medida.Entity = null;
						previousValue.articulo.Remove(this);
					}
					this._unidad_medida.Entity = value;
					if ((value != null))
					{
						value.articulo.Add(this);
						this._id_unidad = value.id_unidad;
					}
					else
					{
						this._id_unidad = default(System.Guid);
					}
					this.SendPropertyChanged("unidad_medida");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_articulo2(articulo entity)
		{
			this.SendPropertyChanging();
			entity.articulo1 = this;
		}
		
		private void detach_articulo2(articulo entity)
		{
			this.SendPropertyChanging();
			entity.articulo1 = null;
		}
		
		private void attach_oferta_articulo(oferta_articulo entity)
		{
			this.SendPropertyChanging();
			entity.articulo = this;
		}
		
		private void detach_oferta_articulo(oferta_articulo entity)
		{
			this.SendPropertyChanging();
			entity.articulo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.empleado")]
	public partial class empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_empleado;
		
		private string _nombre;
		
		private string _a_paterno;
		
		private string _a_materno;
		
		private string _user_name;
		
		private System.DateTime _fecha_registro;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empleadoChanging(System.Guid value);
    partial void Onid_empleadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ona_paternoChanging(string value);
    partial void Ona_paternoChanged();
    partial void Ona_maternoChanging(string value);
    partial void Ona_maternoChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public empleado()
		{
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_paterno", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string a_paterno
		{
			get
			{
				return this._a_paterno;
			}
			set
			{
				if ((this._a_paterno != value))
				{
					this.Ona_paternoChanging(value);
					this.SendPropertyChanging();
					this._a_paterno = value;
					this.SendPropertyChanged("a_paterno");
					this.Ona_paternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_materno", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string a_materno
		{
			get
			{
				return this._a_materno;
			}
			set
			{
				if ((this._a_materno != value))
				{
					this.Ona_maternoChanging(value);
					this.SendPropertyChanging();
					this._a_materno = value;
					this.SendPropertyChanged("a_materno");
					this.Ona_maternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_empleado", Storage="_usuario", ThisKey="user_name", OtherKey="user_name", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.empleado.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.empleado.Add(this);
						this._user_name = value.user_name;
					}
					else
					{
						this._user_name = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.empresa")]
	public partial class empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _rfc;
		
		private string _razon_social;
		
		private string _representante;
		
		private string _calle;
		
		private string _no_ext;
		
		private string _no_int;
		
		private string _colonia;
		
		private string _municipio;
		
		private string _estado;
		
		private string _pais;
		
		private string _codigo_postal;
		
		private string _tel_principal;
		
		private string _e_mail;
		
		private System.Data.Linq.Binary _logo;
		
		private System.DateTime _fecha_registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrfcChanging(string value);
    partial void OnrfcChanged();
    partial void Onrazon_socialChanging(string value);
    partial void Onrazon_socialChanged();
    partial void OnrepresentanteChanging(string value);
    partial void OnrepresentanteChanged();
    partial void OncalleChanging(string value);
    partial void OncalleChanged();
    partial void Onno_extChanging(string value);
    partial void Onno_extChanged();
    partial void Onno_intChanging(string value);
    partial void Onno_intChanged();
    partial void OncoloniaChanging(string value);
    partial void OncoloniaChanged();
    partial void OnmunicipioChanging(string value);
    partial void OnmunicipioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    partial void Oncodigo_postalChanging(string value);
    partial void Oncodigo_postalChanged();
    partial void Ontel_principalChanging(string value);
    partial void Ontel_principalChanged();
    partial void One_mailChanging(string value);
    partial void One_mailChanged();
    partial void OnlogoChanging(System.Data.Linq.Binary value);
    partial void OnlogoChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public empresa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfc", DbType="VarChar(18) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string rfc
		{
			get
			{
				return this._rfc;
			}
			set
			{
				if ((this._rfc != value))
				{
					this.OnrfcChanging(value);
					this.SendPropertyChanging();
					this._rfc = value;
					this.SendPropertyChanged("rfc");
					this.OnrfcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razon_social", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string razon_social
		{
			get
			{
				return this._razon_social;
			}
			set
			{
				if ((this._razon_social != value))
				{
					this.Onrazon_socialChanging(value);
					this.SendPropertyChanging();
					this._razon_social = value;
					this.SendPropertyChanged("razon_social");
					this.Onrazon_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_representante", DbType="VarChar(100)")]
		public string representante
		{
			get
			{
				return this._representante;
			}
			set
			{
				if ((this._representante != value))
				{
					this.OnrepresentanteChanging(value);
					this.SendPropertyChanging();
					this._representante = value;
					this.SendPropertyChanged("representante");
					this.OnrepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calle", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string calle
		{
			get
			{
				return this._calle;
			}
			set
			{
				if ((this._calle != value))
				{
					this.OncalleChanging(value);
					this.SendPropertyChanging();
					this._calle = value;
					this.SendPropertyChanged("calle");
					this.OncalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_ext", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string no_ext
		{
			get
			{
				return this._no_ext;
			}
			set
			{
				if ((this._no_ext != value))
				{
					this.Onno_extChanging(value);
					this.SendPropertyChanging();
					this._no_ext = value;
					this.SendPropertyChanged("no_ext");
					this.Onno_extChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_int", DbType="VarChar(20)")]
		public string no_int
		{
			get
			{
				return this._no_int;
			}
			set
			{
				if ((this._no_int != value))
				{
					this.Onno_intChanging(value);
					this.SendPropertyChanging();
					this._no_int = value;
					this.SendPropertyChanged("no_int");
					this.Onno_intChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colonia", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string colonia
		{
			get
			{
				return this._colonia;
			}
			set
			{
				if ((this._colonia != value))
				{
					this.OncoloniaChanging(value);
					this.SendPropertyChanging();
					this._colonia = value;
					this.SendPropertyChanged("colonia");
					this.OncoloniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				if ((this._municipio != value))
				{
					this.OnmunicipioChanging(value);
					this.SendPropertyChanging();
					this._municipio = value;
					this.SendPropertyChanged("municipio");
					this.OnmunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this.OnpaisChanging(value);
					this.SendPropertyChanging();
					this._pais = value;
					this.SendPropertyChanged("pais");
					this.OnpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_postal", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigo_postal
		{
			get
			{
				return this._codigo_postal;
			}
			set
			{
				if ((this._codigo_postal != value))
				{
					this.Oncodigo_postalChanging(value);
					this.SendPropertyChanging();
					this._codigo_postal = value;
					this.SendPropertyChanged("codigo_postal");
					this.Oncodigo_postalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_principal", DbType="VarChar(30)")]
		public string tel_principal
		{
			get
			{
				return this._tel_principal;
			}
			set
			{
				if ((this._tel_principal != value))
				{
					this.Ontel_principalChanging(value);
					this.SendPropertyChanging();
					this._tel_principal = value;
					this.SendPropertyChanged("tel_principal");
					this.Ontel_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="VarChar(100)")]
		public string e_mail
		{
			get
			{
				return this._e_mail;
			}
			set
			{
				if ((this._e_mail != value))
				{
					this.One_mailChanging(value);
					this.SendPropertyChanging();
					this._e_mail = value;
					this.SendPropertyChanged("e_mail");
					this.One_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.factura_venta")]
	public partial class factura_venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pos;
		
		private System.Guid _id_venta;
		
		private long _id_factura;
		
		private System.DateTime _fecha_registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_posChanging(int value);
    partial void Onid_posChanged();
    partial void Onid_ventaChanging(System.Guid value);
    partial void Onid_ventaChanged();
    partial void Onid_facturaChanging(long value);
    partial void Onid_facturaChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public factura_venta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pos", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pos
		{
			get
			{
				return this._id_pos;
			}
			set
			{
				if ((this._id_pos != value))
				{
					this.Onid_posChanging(value);
					this.SendPropertyChanging();
					this._id_pos = value;
					this.SendPropertyChanged("id_pos");
					this.Onid_posChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", DbType="BigInt NOT NULL")]
		public long id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oferta")]
	public partial class oferta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_oferta;
		
		private long _num_oferta;
		
		private string _descripcion;
		
		private System.DateTime _fecha_oferta;
		
		private System.DateTime _fecha_ini;
		
		private System.DateTime _fecha_fin;
		
		private string _status_oferta;
		
		private System.Nullable<System.DateTime> _fecha_cancelacion;
		
		private string _user_name;
		
		private EntitySet<oferta_articulo> _oferta_articulo;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ofertaChanging(System.Guid value);
    partial void Onid_ofertaChanged();
    partial void Onnum_ofertaChanging(long value);
    partial void Onnum_ofertaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_ofertaChanging(System.DateTime value);
    partial void Onfecha_ofertaChanged();
    partial void Onfecha_iniChanging(System.DateTime value);
    partial void Onfecha_iniChanged();
    partial void Onfecha_finChanging(System.DateTime value);
    partial void Onfecha_finChanged();
    partial void Onstatus_ofertaChanging(string value);
    partial void Onstatus_ofertaChanged();
    partial void Onfecha_cancelacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_cancelacionChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    #endregion
		
		public oferta()
		{
			this._oferta_articulo = new EntitySet<oferta_articulo>(new Action<oferta_articulo>(this.attach_oferta_articulo), new Action<oferta_articulo>(this.detach_oferta_articulo));
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_oferta", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_oferta
		{
			get
			{
				return this._id_oferta;
			}
			set
			{
				if ((this._id_oferta != value))
				{
					this.Onid_ofertaChanging(value);
					this.SendPropertyChanging();
					this._id_oferta = value;
					this.SendPropertyChanged("id_oferta");
					this.Onid_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_oferta", DbType="BigInt NOT NULL")]
		public long num_oferta
		{
			get
			{
				return this._num_oferta;
			}
			set
			{
				if ((this._num_oferta != value))
				{
					this.Onnum_ofertaChanging(value);
					this.SendPropertyChanging();
					this._num_oferta = value;
					this.SendPropertyChanged("num_oferta");
					this.Onnum_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_oferta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_oferta
		{
			get
			{
				return this._fecha_oferta;
			}
			set
			{
				if ((this._fecha_oferta != value))
				{
					this.Onfecha_ofertaChanging(value);
					this.SendPropertyChanging();
					this._fecha_oferta = value;
					this.SendPropertyChanged("fecha_oferta");
					this.Onfecha_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ini", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_ini
		{
			get
			{
				return this._fecha_ini;
			}
			set
			{
				if ((this._fecha_ini != value))
				{
					this.Onfecha_iniChanging(value);
					this.SendPropertyChanging();
					this._fecha_ini = value;
					this.SendPropertyChanged("fecha_ini");
					this.Onfecha_iniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_oferta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string status_oferta
		{
			get
			{
				return this._status_oferta;
			}
			set
			{
				if ((this._status_oferta != value))
				{
					this.Onstatus_ofertaChanging(value);
					this.SendPropertyChanging();
					this._status_oferta = value;
					this.SendPropertyChanged("status_oferta");
					this.Onstatus_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cancelacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_cancelacion
		{
			get
			{
				return this._fecha_cancelacion;
			}
			set
			{
				if ((this._fecha_cancelacion != value))
				{
					this.Onfecha_cancelacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_cancelacion = value;
					this.SendPropertyChanged("fecha_cancelacion");
					this.Onfecha_cancelacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(15)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oferta_oferta_articulo", Storage="_oferta_articulo", ThisKey="id_oferta", OtherKey="id_oferta")]
		public EntitySet<oferta_articulo> oferta_articulo
		{
			get
			{
				return this._oferta_articulo;
			}
			set
			{
				this._oferta_articulo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_oferta", Storage="_usuario", ThisKey="user_name", OtherKey="user_name", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.oferta.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.oferta.Add(this);
						this._user_name = value.user_name;
					}
					else
					{
						this._user_name = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oferta_articulo(oferta_articulo entity)
		{
			this.SendPropertyChanging();
			entity.oferta = this;
		}
		
		private void detach_oferta_articulo(oferta_articulo entity)
		{
			this.SendPropertyChanging();
			entity.oferta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oferta_articulo")]
	public partial class oferta_articulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_oferta;
		
		private string _cod_barras;
		
		private decimal _precio_oferta;
		
		private string _status_oferta;
		
		private System.Nullable<System.DateTime> _fecha_cancelacion;
		
		private System.DateTime _fecha_registro;
		
		private EntityRef<articulo> _articulo;
		
		private EntityRef<oferta> _oferta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ofertaChanging(System.Guid value);
    partial void Onid_ofertaChanged();
    partial void Oncod_barrasChanging(string value);
    partial void Oncod_barrasChanged();
    partial void Onprecio_ofertaChanging(decimal value);
    partial void Onprecio_ofertaChanged();
    partial void Onstatus_ofertaChanging(string value);
    partial void Onstatus_ofertaChanged();
    partial void Onfecha_cancelacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_cancelacionChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public oferta_articulo()
		{
			this._articulo = default(EntityRef<articulo>);
			this._oferta = default(EntityRef<oferta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_oferta", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_oferta
		{
			get
			{
				return this._id_oferta;
			}
			set
			{
				if ((this._id_oferta != value))
				{
					if (this._oferta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ofertaChanging(value);
					this.SendPropertyChanging();
					this._id_oferta = value;
					this.SendPropertyChanged("id_oferta");
					this.Onid_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_barras", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cod_barras
		{
			get
			{
				return this._cod_barras;
			}
			set
			{
				if ((this._cod_barras != value))
				{
					if (this._articulo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_barrasChanging(value);
					this.SendPropertyChanging();
					this._cod_barras = value;
					this.SendPropertyChanged("cod_barras");
					this.Oncod_barrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_oferta", DbType="Decimal(19,3) NOT NULL")]
		public decimal precio_oferta
		{
			get
			{
				return this._precio_oferta;
			}
			set
			{
				if ((this._precio_oferta != value))
				{
					this.Onprecio_ofertaChanging(value);
					this.SendPropertyChanging();
					this._precio_oferta = value;
					this.SendPropertyChanged("precio_oferta");
					this.Onprecio_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_oferta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string status_oferta
		{
			get
			{
				return this._status_oferta;
			}
			set
			{
				if ((this._status_oferta != value))
				{
					this.Onstatus_ofertaChanging(value);
					this.SendPropertyChanging();
					this._status_oferta = value;
					this.SendPropertyChanged("status_oferta");
					this.Onstatus_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cancelacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_cancelacion
		{
			get
			{
				return this._fecha_cancelacion;
			}
			set
			{
				if ((this._fecha_cancelacion != value))
				{
					this.Onfecha_cancelacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_cancelacion = value;
					this.SendPropertyChanged("fecha_cancelacion");
					this.Onfecha_cancelacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="articulo_oferta_articulo", Storage="_articulo", ThisKey="cod_barras", OtherKey="cod_barras", IsForeignKey=true)]
		public articulo articulo
		{
			get
			{
				return this._articulo.Entity;
			}
			set
			{
				articulo previousValue = this._articulo.Entity;
				if (((previousValue != value) 
							|| (this._articulo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._articulo.Entity = null;
						previousValue.oferta_articulo.Remove(this);
					}
					this._articulo.Entity = value;
					if ((value != null))
					{
						value.oferta_articulo.Add(this);
						this._cod_barras = value.cod_barras;
					}
					else
					{
						this._cod_barras = default(string);
					}
					this.SendPropertyChanged("articulo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oferta_oferta_articulo", Storage="_oferta", ThisKey="id_oferta", OtherKey="id_oferta", IsForeignKey=true)]
		public oferta oferta
		{
			get
			{
				return this._oferta.Entity;
			}
			set
			{
				oferta previousValue = this._oferta.Entity;
				if (((previousValue != value) 
							|| (this._oferta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oferta.Entity = null;
						previousValue.oferta_articulo.Remove(this);
					}
					this._oferta.Entity = value;
					if ((value != null))
					{
						value.oferta_articulo.Add(this);
						this._id_oferta = value.id_oferta;
					}
					else
					{
						this._id_oferta = default(System.Guid);
					}
					this.SendPropertyChanged("oferta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.permiso")]
	public partial class permiso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_permiso;
		
		private string _descripcion;
		
		private string _tipo_sistema;
		
		private System.DateTime _fecha_registro;
		
		private EntitySet<usuario_permiso> _usuario_permiso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_permisoChanging(string value);
    partial void Onid_permisoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Ontipo_sistemaChanging(string value);
    partial void Ontipo_sistemaChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public permiso()
		{
			this._usuario_permiso = new EntitySet<usuario_permiso>(new Action<usuario_permiso>(this.attach_usuario_permiso), new Action<usuario_permiso>(this.detach_usuario_permiso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_permiso", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_permiso
		{
			get
			{
				return this._id_permiso;
			}
			set
			{
				if ((this._id_permiso != value))
				{
					this.Onid_permisoChanging(value);
					this.SendPropertyChanging();
					this._id_permiso = value;
					this.SendPropertyChanged("id_permiso");
					this.Onid_permisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_sistema", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo_sistema
		{
			get
			{
				return this._tipo_sistema;
			}
			set
			{
				if ((this._tipo_sistema != value))
				{
					this.Ontipo_sistemaChanging(value);
					this.SendPropertyChanging();
					this._tipo_sistema = value;
					this.SendPropertyChanged("tipo_sistema");
					this.Ontipo_sistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="permiso_usuario_permiso", Storage="_usuario_permiso", ThisKey="id_permiso", OtherKey="id_permiso")]
		public EntitySet<usuario_permiso> usuario_permiso
		{
			get
			{
				return this._usuario_permiso;
			}
			set
			{
				this._usuario_permiso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_usuario_permiso(usuario_permiso entity)
		{
			this.SendPropertyChanging();
			entity.permiso = this;
		}
		
		private void detach_usuario_permiso(usuario_permiso entity)
		{
			this.SendPropertyChanging();
			entity.permiso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.unidad_medida")]
	public partial class unidad_medida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id_unidad;
		
		private string _descripcion;
		
		private System.DateTime _fecha_registro;
		
		private string _cve_sat;
		
		private EntitySet<articulo> _articulo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_unidadChanging(System.Guid value);
    partial void Onid_unidadChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    partial void Oncve_satChanging(string value);
    partial void Oncve_satChanged();
    #endregion
		
		public unidad_medida()
		{
			this._articulo = new EntitySet<articulo>(new Action<articulo>(this.attach_articulo), new Action<articulo>(this.detach_articulo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_unidad", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id_unidad
		{
			get
			{
				return this._id_unidad;
			}
			set
			{
				if ((this._id_unidad != value))
				{
					this.Onid_unidadChanging(value);
					this.SendPropertyChanging();
					this._id_unidad = value;
					this.SendPropertyChanged("id_unidad");
					this.Onid_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cve_sat", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cve_sat
		{
			get
			{
				return this._cve_sat;
			}
			set
			{
				if ((this._cve_sat != value))
				{
					this.Oncve_satChanging(value);
					this.SendPropertyChanging();
					this._cve_sat = value;
					this.SendPropertyChanged("cve_sat");
					this.Oncve_satChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidad_medida_articulo", Storage="_articulo", ThisKey="id_unidad", OtherKey="id_unidad")]
		public EntitySet<articulo> articulo
		{
			get
			{
				return this._articulo;
			}
			set
			{
				this._articulo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_articulo(articulo entity)
		{
			this.SendPropertyChanging();
			entity.unidad_medida = this;
		}
		
		private void detach_articulo(articulo entity)
		{
			this.SendPropertyChanging();
			entity.unidad_medida = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario_permiso")]
	public partial class usuario_permiso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_name;
		
		private string _id_permiso;
		
		private System.Nullable<decimal> _valor_num;
		
		private System.DateTime _fecha_registro;
		
		private EntityRef<permiso> _permiso;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onid_permisoChanging(string value);
    partial void Onid_permisoChanged();
    partial void Onvalor_numChanging(System.Nullable<decimal> value);
    partial void Onvalor_numChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public usuario_permiso()
		{
			this._permiso = default(EntityRef<permiso>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_permiso", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_permiso
		{
			get
			{
				return this._id_permiso;
			}
			set
			{
				if ((this._id_permiso != value))
				{
					if (this._permiso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_permisoChanging(value);
					this.SendPropertyChanging();
					this._id_permiso = value;
					this.SendPropertyChanged("id_permiso");
					this.Onid_permisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_num", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> valor_num
		{
			get
			{
				return this._valor_num;
			}
			set
			{
				if ((this._valor_num != value))
				{
					this.Onvalor_numChanging(value);
					this.SendPropertyChanging();
					this._valor_num = value;
					this.SendPropertyChanged("valor_num");
					this.Onvalor_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="permiso_usuario_permiso", Storage="_permiso", ThisKey="id_permiso", OtherKey="id_permiso", IsForeignKey=true)]
		public permiso permiso
		{
			get
			{
				return this._permiso.Entity;
			}
			set
			{
				permiso previousValue = this._permiso.Entity;
				if (((previousValue != value) 
							|| (this._permiso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._permiso.Entity = null;
						previousValue.usuario_permiso.Remove(this);
					}
					this._permiso.Entity = value;
					if ((value != null))
					{
						value.usuario_permiso.Add(this);
						this._id_permiso = value.id_permiso;
					}
					else
					{
						this._id_permiso = default(string);
					}
					this.SendPropertyChanged("permiso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_usuario_permiso", Storage="_usuario", ThisKey="user_name", OtherKey="user_name", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.usuario_permiso.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.usuario_permiso.Add(this);
						this._user_name = value.user_name;
					}
					else
					{
						this._user_name = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_name;
		
		private string _password;
		
		private string _tipo_usuario;
		
		private bool _enable;
		
		private System.Nullable<short> _user_code_bascula;
		
		private System.DateTime _fecha_registro;
		
		private EntitySet<empleado> _empleado;
		
		private EntitySet<oferta> _oferta;
		
		private EntitySet<usuario_permiso> _usuario_permiso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Ontipo_usuarioChanging(string value);
    partial void Ontipo_usuarioChanged();
    partial void OnenableChanging(bool value);
    partial void OnenableChanged();
    partial void Onuser_code_basculaChanging(System.Nullable<short> value);
    partial void Onuser_code_basculaChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public usuario()
		{
			this._empleado = new EntitySet<empleado>(new Action<empleado>(this.attach_empleado), new Action<empleado>(this.detach_empleado));
			this._oferta = new EntitySet<oferta>(new Action<oferta>(this.attach_oferta), new Action<oferta>(this.detach_oferta));
			this._usuario_permiso = new EntitySet<usuario_permiso>(new Action<usuario_permiso>(this.attach_usuario_permiso), new Action<usuario_permiso>(this.detach_usuario_permiso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tipo_usuario
		{
			get
			{
				return this._tipo_usuario;
			}
			set
			{
				if ((this._tipo_usuario != value))
				{
					this.Ontipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._tipo_usuario = value;
					this.SendPropertyChanged("tipo_usuario");
					this.Ontipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enable", DbType="Bit NOT NULL")]
		public bool enable
		{
			get
			{
				return this._enable;
			}
			set
			{
				if ((this._enable != value))
				{
					this.OnenableChanging(value);
					this.SendPropertyChanging();
					this._enable = value;
					this.SendPropertyChanged("enable");
					this.OnenableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_code_bascula", DbType="SmallInt")]
		public System.Nullable<short> user_code_bascula
		{
			get
			{
				return this._user_code_bascula;
			}
			set
			{
				if ((this._user_code_bascula != value))
				{
					this.Onuser_code_basculaChanging(value);
					this.SendPropertyChanging();
					this._user_code_bascula = value;
					this.SendPropertyChanged("user_code_bascula");
					this.Onuser_code_basculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_empleado", Storage="_empleado", ThisKey="user_name", OtherKey="user_name")]
		public EntitySet<empleado> empleado
		{
			get
			{
				return this._empleado;
			}
			set
			{
				this._empleado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_oferta", Storage="_oferta", ThisKey="user_name", OtherKey="user_name")]
		public EntitySet<oferta> oferta
		{
			get
			{
				return this._oferta;
			}
			set
			{
				this._oferta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_usuario_permiso", Storage="_usuario_permiso", ThisKey="user_name", OtherKey="user_name")]
		public EntitySet<usuario_permiso> usuario_permiso
		{
			get
			{
				return this._usuario_permiso;
			}
			set
			{
				this._usuario_permiso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_empleado(empleado entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_empleado(empleado entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_oferta(oferta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_oferta(oferta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_usuario_permiso(usuario_permiso entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_usuario_permiso(usuario_permiso entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
}
#pragma warning restore 1591
